import { Navigate, useLocation, useParams } from 'react-router-dom';
import { SeoHead } from '../../components/common/SeoHead';
import { BeforeAfter, Breadcrumbs, breadcrumbSchema, CardGrid, CaseCommercialLinks, CaseStudyGrid, CaseStudyMedia, CaseStudyProcess, EditorialExpansion, EvidenceList, Faqs, faqSchema, FinalCta, GuaranteeBlock, Hero, Pricing, RelatedSolutions, Section, VerifiedMetrics } from '../../components/growth/GrowthBlocks';
import { auditFaqs, contactConfig, DOMAIN, getProblemCta, getSolutionConnections, getSolutionFaqs, localPath, markets, planFaqs, plans, problemCatalog, resourceCatalog, solutionCatalog, systemFaqs } from '../../data/growthSystem';
import { caseStudies, getCaseStudyBySlug, getRelatedCaseStudies } from '../../data/caseStudies';
import { getEditorialExpansion } from '../../data/editorialExpansions';

const fit = ['Tiene una oferta definida', 'Ya dispone de sitio web', 'Puede atender oportunidades', 'Puede proporcionar accesos', 'Tiene una persona responsable', 'Entiende que SEO requiere continuidad', 'Puede trabajar durante al menos tres o seis meses'];
const process = ['Auditoría', 'Roadmap', 'Priorización', 'Implementación', 'Automatización', 'Medición', 'Optimización continua'];
const serviceSchema = (market, name, description, path) => ({ '@context': 'https://schema.org', '@type': 'Service', name, description, areaServed: markets[market].name, provider: { '@type': 'Organization', name: 'Pixvo', url: DOMAIN }, url: new URL(path, DOMAIN).toString() });

function useMarket() { const { market } = useParams(); return markets[market] ? market : 'mx'; }
function Head({ market, routePath, title, description, image, imageWidth, imageHeight, schema = [], robots }) { return <SeoHead market={market} routePath={routePath} path={localPath(market, routePath)} title={title} description={description} image={image} imageWidth={imageWidth} imageHeight={imageHeight} robots={robots} schema={schema} />; }

export function RootMarketSelector() {
  return <><SeoHead title="Pixvo | Elige tu mercado" description="Selecciona México, Argentina o España para acceder al contenido y las condiciones de Pixvo en tu mercado." path="/" rootAlternates schema={[{ '@context': 'https://schema.org', '@type': 'WebSite', name: 'Pixvo', url: DOMAIN }, { '@context': 'https://schema.org', '@type': 'Organization', name: 'Pixvo', url: DOMAIN }]} /><section className="market-selector"><div><span className="eyebrow">Pixvo</span><h1>Pixvo Growth System</h1><p>Elige tu mercado para consultar el contenido, las referencias geográficas y las condiciones comerciales correspondientes.</p><h2>Selecciona tu mercado</h2><div className="market-options">{Object.values(markets).map((market) => <a key={market.code} href={`/${market.code}/`} aria-label={`Ver Pixvo para ${market.name}`} onClick={() => window.dataLayer?.push({ event: 'country_select', country: market.code, currency: market.currency })}><CountryFlag code={market.code} name={market.name} /><strong>{market.name}</strong><span>Contenido y condiciones para {market.name}</span></a>)}</div></div></section></>;
}

function CountryFlag({ code, name }) {
  if (code === 'mx') return <svg className="market-flag" viewBox="0 0 48 32" role="img" aria-label={`Bandera de ${name}`}><rect width="16" height="32" fill="#006847"/><rect x="16" width="16" height="32" fill="#fff"/><rect x="32" width="16" height="32" fill="#ce1126"/><circle cx="24" cy="16" r="3.2" fill="#8b6b2f"/><path d="M21 19c2 2 4 2 6 0" fill="none" stroke="#28734f" strokeWidth="1.2"/></svg>;
  if (code === 'ar') return <svg className="market-flag" viewBox="0 0 48 32" role="img" aria-label={`Bandera de ${name}`}><rect width="48" height="32" fill="#74acdf"/><rect y="10.66" width="48" height="10.68" fill="#fff"/><circle cx="24" cy="16" r="3" fill="#f6b40e"/><path d="M24 11v2m0 6v2m-5-5h2m6 0h2" stroke="#f6b40e" strokeWidth="1"/></svg>;
  return <svg className="market-flag" viewBox="0 0 48 32" role="img" aria-label={`Bandera de ${name}`}><rect width="48" height="32" fill="#aa151b"/><rect y="8" width="48" height="16" fill="#f1bf00"/><rect x="14" y="12" width="4" height="8" rx=".6" fill="#aa151b"/><rect x="13" y="11" width="6" height="1.5" fill="#fff"/></svg>;
}

export function MarketHome() {
  const { market: requested } = useParams();
  const market = useMarket(); const routePath = '';
  if (!markets[requested]) return <Navigate to="/404" replace />;
  const solutions = [
    ['SEO para PyMEs', 'seo-para-pymes'], ['Contenido y landings', 'contenido-seo'], ['Automatización de procesos', 'automatizacion-de-procesos'], ['Seguimiento de leads', 'seguimiento-de-leads'], ['Analítica digital', 'analitica-digital'], ['Optimización WordPress', 'optimizacion-wordpress'], ['Optimización de conversión', 'optimizacion-de-conversion'],
  ];
  const problemCards = [
    ['Tu empresa no aparece cuando buscan sus servicios', 'dependencia-publicidad-paga'],
    ['Dependes demasiado de publicidad pagada', 'dependencia-publicidad-paga'],
    ['Tu web recibe visitas, pero genera pocas consultas', 'web-no-convierte'],
    ['Los leads llegan sin un seguimiento claro', 'leads-no-convierten'],
    ['Tu equipo repite tareas que podrían automatizarse', 'reducir-tareas-manuales'],
    ['No sabes qué acciones producen oportunidades', 'medir-resultados-marketing'],
  ].map(([title, slug]) => ({ title, to: localPath(market, `problemas/${slug}`), link: 'Analizar este problema' }));
  return <>
    <Head market={market} routePath={routePath} title="Pixvo | SEO, automatización y crecimiento para PyMEs" description={`Pixvo conecta SEO, automatización y analítica para ayudar a PyMEs de ${markets[market].name} a mejorar su visibilidad y aprovechar mejor sus oportunidades.`} />
    <Hero market={market} title="Pixvo: SEO, automatización y analítica para PyMEs" lead={`Conectamos visibilidad, procesos y datos para ayudar a empresas de ${markets[market].name} a generar oportunidades y aprovecharlas mejor.`} secondary={{ label: 'Ver cómo funciona', to: localPath(market, 'sistema-crecimiento-digital') }} />
    <Section title="Tu empresa no necesita más herramientas desconectadas" intro="Muchas empresas invierten en una web, contenidos, publicidad y software sin disponer de un sistema que conecte captación, conversión y seguimiento. El resultado: poca visibilidad, tareas manuales, consultas tardías y métricas que no ayudan a decidir."><CardGrid items={problemCards} /></Section>
    <Section tone="section-tint" title="SEO, automatización y analítica dentro de un mismo sistema" intro="No vendemos horas de desarrollo ni tareas técnicas desconectadas. Auditamos el sistema, priorizamos mejoras, implementamos acciones y medimos qué está funcionando."><CardGrid items={solutions.map(([title, slug]) => ({ title, to: localPath(market, `soluciones/${slug}`), link: `Conocer ${title.toLowerCase()}` }))} /></Section>
    <Section title="Cómo funciona Pixvo Growth System"><CardGrid items={process} columns={4} /></Section>
    <Section title="No entregamos únicamente tráfico e informes" intro="Analizamos cómo llegan las oportunidades, qué páginas deberían convertir, cuánto tarda la respuesta y en qué etapa se pierden los contactos. Pixvo no reemplaza a tu equipo comercial: le proporciona mejores procesos, información y automatizaciones." />
    <Section title="Planes transparentes y alcance definido" intro="Elige un plan de mejora continua según la madurez de tu empresa, las acciones necesarias y el nivel de automatización requerido."><a className="button button--secondary" href={localPath(market, 'planes')}>Ver planes y precios</a></Section>
    <Section title="Una colaboración orientada a resultados" intro="El sistema funciona mejor cuando existe un objetivo claro, una persona responsable y capacidad para implementar, medir y mejorar de forma continua."><div className="fit-grid fit-grid--single"><div><h3>Condiciones que ayudan a avanzar</h3><ul>{fit.map((x) => <li key={x}>{x}</li>)}</ul></div></div></Section>
    <EditorialExpansion sections={getEditorialExpansion({ pageType: 'home', marketCode: market })} />
    <FinalCta market={market} />
  </>;
}

export function SystemPage() {
  const market = useMarket(), routePath = 'sistema-crecimiento-digital'; const crumbs = [{ label: 'Sistema de crecimiento', path: localPath(market, routePath) }];
  const available = Object.keys(solutionCatalog);
  const systemProblems = [
    ['Visibilidad orgánica insuficiente', 'dependencia-publicidad-paga'],
    ['Tareas repetitivas y errores', 'reducir-tareas-manuales'],
    ['Leads sin seguimiento', 'leads-no-convierten'],
    ['Web que no convierte', 'web-no-convierte'],
    ['Medición fragmentada', 'medir-resultados-marketing'],
    ['Marketing y ventas desconectados', 'conectar-marketing-y-ventas'],
    ['WordPress lento', 'wordpress-lento'],
    ['Contenido sin ruta comercial', 'contenido-no-genera-clientes'],
  ].map(([title, slug]) => ({ title, to: localPath(market, `problemas/${slug}`), link: 'Entender el problema' }));
  return <>
    <Head market={market} routePath={routePath} title="Sistema de crecimiento digital para PyMEs | Pixvo" description="Integramos SEO, automatización, WordPress, analítica y seguimiento de leads en un sistema de mejora continua para PyMEs." schema={[serviceSchema(market, 'Pixvo Growth System', 'Sistema de crecimiento digital para PyMEs.', localPath(market, routePath)), breadcrumbSchema(market, crumbs), faqSchema(systemFaqs)]} />
    <Breadcrumbs market={market} items={[{ label: 'Sistema de crecimiento' }]} />
    <Hero market={market} title="Sistema de crecimiento digital para PyMEs" lead="Una estrategia de crecimiento digital que conecta visibilidad, conversión, automatización, seguimiento y medición." secondary={{ label: 'Solicitar una auditoría', to: localPath(market, 'auditoria-crecimiento-digital') }} />
    <Section title="Un sistema, no una colección de servicios aislados" intro="La consultoría de crecimiento digital parte del cuello de botella y organiza SEO, automatización y analítica dentro de un roadmap común: captar demanda relevante, mejorar la conversión, automatizar tareas y medir cada oportunidad." />
    <Section title="Qué problemas resuelve"><CardGrid items={systemProblems} /></Section>
    <Section title="Qué incluye el sistema"><RelatedSolutions market={market} slugs={available} /></Section>
    <Section title="Cómo se prioriza el trabajo"><CardGrid items={process} columns={4} /></Section>
    <Section title="Decisiones que conviene resolver antes de implementar"><CardGrid items={['seo-vs-sistema-de-crecimiento', 'seo-mensual-vs-auditoria'].map((slug) => ({ title: resourceCatalog[slug].title, text: resourceCatalog[slug].decision, to: localPath(market, `recursos/${slug}`), link: 'Comparar alternativas' }))} /></Section>
    <Section title="Transformaciones relacionadas"><CaseStudyGrid items={['microcuotas', 'sanidad-web'].map(getCaseStudyBySlug).filter(Boolean)} market={market} /></Section>
    <Section title="Auditoría y planes"><RelatedSolutions market={market} slugs={['auditoria-crecimiento-digital', 'planes']} /></Section>
    <EditorialExpansion sections={getEditorialExpansion({ pageType: 'commercial_hub', marketCode: market })} />
    <Section title="Preguntas frecuentes"><Faqs items={systemFaqs} /></Section>
    <FinalCta market={market} actionLabel="Diagnosticar mi sistema de crecimiento" />
  </>;
}

export function PlansPage() {
  const market = useMarket(), routePath = 'planes'; const crumbs = [{ label: 'Planes', path: localPath(market, routePath) }];
  const offers = market === 'es' ? plans.map((p) => ({ '@type': 'Offer', name: p.name, priceCurrency: 'EUR', price: String({ core: 550, growth: 800, scale: 1200 }[p.id]), url: new URL(localPath(market, routePath), DOMAIN).toString() })) : undefined;
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: 'Planes de Pixvo Growth System', provider: { '@type': 'Organization', name: 'Pixvo' }, areaServed: markets[market].name, ...(offers ? { offers } : {}) };
  return <><Head market={market} routePath={routePath} title="Planes y precios de Pixvo Growth System" description="Compara precios y planes de crecimiento digital para PyMEs: alcance SEO, automatización, permanencia, KPI y capacidad operativa." schema={[schema, breadcrumbSchema(market, crumbs), faqSchema(planFaqs)]} /><Breadcrumbs market={market} items={[{ label: 'Planes' }]} /><Hero market={market} title="Planes y precios de Pixvo Growth System" lead="Cada plan define qué puede priorizarse cada mes, qué seguimiento incluye y cuánta capacidad operativa está disponible. No ofrecemos tareas ilimitadas." secondary={{ label: 'Entender el sistema', to: localPath(market, 'sistema-crecimiento-digital') }} /><Section title={`Planes de crecimiento digital disponibles en ${markets[market].name}`} intro={`Los importes se muestran en ${markets[market].currency} solo cuando están aprobados. El onboarding se presenta por separado. El precio SEO para PyMEs depende del alcance, la línea base y la capacidad de implementación.`}><Pricing market={market} /></Section><Section tone="section-tint" title="Una garantía basada en tráfico medible, no en promesas de venta"><GuaranteeBlock /></Section><Section title="Antes de elegir un plan"><RelatedSolutions market={market} slugs={['sistema-crecimiento-digital', 'auditoria-crecimiento-digital']} /></Section><Section title="Auditoría o trabajo mensual"><CardGrid items={[{ title: resourceCatalog['seo-mensual-vs-auditoria'].title, text: resourceCatalog['seo-mensual-vs-auditoria'].decision, to: localPath(market, 'recursos/seo-mensual-vs-auditoria'), link: 'Comparar las dos opciones' }]} /></Section><Section title="Un caso de automatización y seguimiento"><CaseStudyGrid items={[getCaseStudyBySlug('microcuotas')].filter(Boolean)} market={market} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'pricing', marketCode: market })} /><Section title="Preguntas frecuentes sobre planes"><Faqs items={planFaqs} /></Section><FinalCta market={market} title="Elige un plan a partir de tu capacidad real" description="Comparte tu situación, los accesos disponibles y la capacidad de implementación. La recomendación debe ajustarse al alcance, no al plan más grande." actionLabel="Revisar qué plan encaja" /></>;
}

export function AuditPage() {
  const market = useMarket(), routePath = 'auditoria-crecimiento-digital'; const crumbs = [{ label: 'Auditoría', path: localPath(market, routePath) }];
  return <><Head market={market} routePath={routePath} title="Auditoría de crecimiento digital, SEO y conversión | Pixvo" description="Auditoría de marketing digital, SEO y conversión para detectar cuellos de botella y obtener un roadmap priorizado." schema={[serviceSchema(market, 'Auditoría de crecimiento digital', 'Auditoría SEO y conversión del recorrido desde captación hasta seguimiento.', localPath(market, routePath)), breadcrumbSchema(market, crumbs), faqSchema(auditFaqs)]} /><Breadcrumbs market={market} items={[{ label: 'Auditoría' }]} /><Hero market={market} eyebrow="Auditoría" title="Auditoría de crecimiento digital, SEO y conversión" lead="Analizamos el recorrido completo desde que una persona descubre tu empresa hasta que se convierte —o no— en cliente." secondary={{ label: 'Entender el sistema', to: localPath(market, 'sistema-crecimiento-digital') }} /><Section title="El problema puede no estar donde crees" intro="Una auditoría de marketing digital separa captación, experiencia, conversión y seguimiento. Más tráfico no soluciona una web que no convierte; más formularios no ayudan si nadie responde a tiempo." /><Section title="Qué analizamos"><CardGrid items={['Relevancia del tráfico y visibilidad', 'Arquitectura y páginas de conversión', 'Formularios y tracking', 'Tiempo de respuesta y seguimiento', 'Automatizaciones e integración', 'Cuellos de botella']} /></Section><Section title="Qué recibes"><CardGrid items={['Diagnóstico', 'Problemas priorizados', 'Riesgos y oportunidades', 'Roadmap', 'Recomendaciones', 'Plan sugerido cuando exista encaje']} /></Section><Section title="Áreas que puede priorizar la auditoría"><RelatedSolutions market={market} slugs={['seo-para-pymes', 'automatizacion-de-procesos', 'seguimiento-de-leads']} /></Section><Section title="Auditoría puntual o plan de implementación"><CardGrid items={[{ title: resourceCatalog['seo-mensual-vs-auditoria'].title, text: resourceCatalog['seo-mensual-vs-auditoria'].decision, to: localPath(market, 'recursos/seo-mensual-vs-auditoria'), link: 'Comparar alternativas' }, { title: 'Planes de Pixvo Growth System', text: 'Compara capacidad, permanencia, precios disponibles y límites del trabajo recurrente.', to: localPath(market, 'planes'), link: 'Ver planes y precios' }]} /></Section><Section title="Evidencia de un funnel diagnosticado e integrado"><CaseStudyGrid items={[getCaseStudyBySlug('microcuotas')].filter(Boolean)} market={market} /></Section><Section title="Limitaciones de la trazabilidad" intro="La calidad del diagnóstico depende de los accesos y datos disponibles. Señalamos las lagunas de medición y no completamos datos ausentes con estimaciones." /><EditorialExpansion sections={getEditorialExpansion({ pageType: 'audit', marketCode: market })} /><Section title="Preguntas frecuentes sobre la auditoría"><Faqs items={auditFaqs} /></Section><FinalCta market={market} title="Solicitar una auditoría de crecimiento digital" actionLabel="Solicitar la auditoría" /></>;
}

export function SolutionPage() {
  const market = useMarket(), { slug } = useParams(); const data = solutionCatalog[slug];
  if (!data) return <Navigate to="/404" replace />;
  const routePath = `soluciones/${slug}`, crumbs = [{ label: 'Soluciones', path: localPath(market, 'sistema-crecimiento-digital') }, { label: data.title, path: localPath(market, routePath) }];
  const connections = getSolutionConnections(slug);
  const solutionFaqs = getSolutionFaqs(slug);
  return <><Head market={market} routePath={routePath} title={`${data.title} | Pixvo`} description={data.description || `${data.lead} Conoce el alcance, los límites y cómo se integra en Pixvo Growth System.`} schema={[serviceSchema(market, data.title, data.lead, localPath(market, routePath)), breadcrumbSchema(market, crumbs), faqSchema(solutionFaqs)]} /><Breadcrumbs market={market} items={[{ label: 'Sistema de crecimiento', to: localPath(market, 'sistema-crecimiento-digital') }, { label: data.title }]} /><Hero market={market} eyebrow="Solución" title={data.h1} lead={data.lead} secondary={{ label: 'Ver el sistema completo', to: localPath(market, 'sistema-crecimiento-digital') }} /><Section title="El resultado comercial guía la prioridad" intro="No implementamos tareas aisladas por acumular entregables. Primero identificamos el cuello de botella, después priorizamos una mejora verificable y la conectamos con el resto del sistema." /><Section title="Qué trabajamos"><CardGrid items={data.items} /></Section><Section title="Cómo priorizamos"><CardGrid items={['Impacto esperado', 'Evidencia disponible', 'Esfuerzo y dependencias', 'Capacidad del equipo', 'Medición posible']} /></Section>{data.excluded && <Section title="Qué no equivale a este servicio"><CardGrid items={data.excluded} /></Section>}{connections.problems.length > 0 && <Section title="Problemas que ayuda a resolver"><CardGrid items={connections.problems.map((item) => ({ title: item.h1, text: item.lead, to: localPath(market, `problemas/${item.slug}`), link: 'Diagnosticar este problema' }))} /></Section>}<Section title="Soluciones relacionadas"><RelatedSolutions market={market} slugs={data.related.slice(0, 3)} /></Section>{connections.resources.length > 0 && <Section title="Comparativas para tomar la decisión"><CardGrid items={connections.resources.map((item) => ({ title: item.title, text: item.decision, to: localPath(market, `recursos/${item.slug}`), link: 'Comparar alternativas' }))} /></Section>}{connections.cases.length > 0 && <Section title="Casos relacionados con esta capacidad"><CaseStudyGrid items={connections.cases} market={market} /></Section>}<Section title="Define el alcance antes de contratar"><RelatedSolutions market={market} slugs={['auditoria-crecimiento-digital', 'planes']} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'solution', marketCode: market, data })} /><Section title={`Preguntas frecuentes sobre ${data.title}`}><Faqs items={solutionFaqs} /></Section><FinalCta market={market} title={`Revisemos si ${data.title.toLowerCase()} encaja con tu prioridad`} actionLabel="Solicitar diagnóstico" /></>;
}

export function ProblemPage() {
  const market = useMarket(), { slug } = useParams(), data = problemCatalog[slug]; if (!data) return <Navigate to="/404" replace />;
  const routePath = `problemas/${slug}`, crumbs = [{ label: 'Problemas', path: localPath(market) }, { label: data.h1, path: localPath(market, routePath) }];
  const conversionPaths = [...new Set([data.conversion, 'auditoria-crecimiento-digital'])];
  return <><Head market={market} routePath={routePath} title={`${data.h1.replace(/[¿?]/g, '')} | Pixvo`} description={`${data.lead} Revisa síntomas, causas, diagnóstico y soluciones comerciales relacionadas.`} schema={[breadcrumbSchema(market, crumbs)]} /><Breadcrumbs market={market} items={[{ label: 'Problemas', to: localPath(market) }, { label: data.h1 }]} /><Hero market={market} eyebrow="Problema" title={data.h1} lead={data.lead} /><Section title="Síntomas que conviene comprobar"><CardGrid items={data.symptoms} /></Section><Section tone="section-tint" title="Causas habituales"><CardGrid items={data.causes} /></Section><Section title="Cómo diagnosticar el cuello de botella" intro="Los síntomas aislados no bastan para decidir. El diagnóstico recorre datos, proceso, responsables y capacidad de respuesta antes de proponer cambios."><CardGrid items={data.diagnosis} /></Section><Section tone="section-tint" title="Soluciones relacionadas con el problema"><RelatedSolutions market={market} slugs={[data.primary, data.secondary]} /></Section><Section title="Auditoría o diagnóstico"><RelatedSolutions market={market} slugs={conversionPaths} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'problem', marketCode: market, data })} /><FinalCta market={market} title="Convierte los síntomas en un diagnóstico accionable" actionLabel={getProblemCta(slug)} target={data.conversion} /></>;
}

export function ResourcesIndex() { const market = useMarket(); return <><Head market={market} routePath="recursos" title="Recursos para decidir cómo crecer | Pixvo" description="Comparativas comerciales sobre SEO, automatización, analítica y conversión para elegir el siguiente paso de una PyME." /><Breadcrumbs market={market} items={[{ label: 'Recursos' }]} /><Hero market={market} eyebrow="Recursos MOFU" title="Decisiones de crecimiento con contexto comercial" lead="Compara alternativas, costes operativos, límites y dependencias antes de elegir una solución." secondary={{ label: 'Ver el sistema completo', to: localPath(market, 'sistema-crecimiento-digital') }} /><Section title="Comparativas disponibles"><CardGrid items={Object.entries(resourceCatalog).map(([slug, data]) => ({ title: data.title, text: data.decision, to: localPath(market, `recursos/${slug}`), link: 'Comparar opciones' }))} /></Section><Section title="Si el problema todavía no está claro"><RelatedSolutions market={market} slugs={['auditoria-crecimiento-digital', 'planes']} /></Section><FinalCta market={market} /></>; }

export function ResourcePage() { const market = useMarket(), { slug } = useParams(), data = resourceCatalog[slug]; if (!data) return <Navigate to="/404" replace />; const routePath = `recursos/${slug}`; return <><Head market={market} routePath={routePath} title={`${data.title} | Guía de decisión de Pixvo`} description={data.lead} type="article" schema={[{ '@context': 'https://schema.org', '@type': 'Article', headline: data.title, description: data.lead, author: { '@type': 'Organization', name: 'Pixvo' }, mainEntityOfPage: new URL(localPath(market, routePath), DOMAIN).toString() }, breadcrumbSchema(market, [{ label: 'Recursos', path: localPath(market, 'recursos') }, { label: data.title, path: localPath(market, routePath) }])]} /><Breadcrumbs market={market} items={[{ label: 'Recursos', to: localPath(market, 'recursos') }, { label: data.title }]} /><Hero market={market} eyebrow="Comparativa comercial" title={data.title} lead={data.lead} secondary={{ label: 'Ver todas las comparativas', to: localPath(market, 'recursos') }} /><Section title="Qué decisión ayuda a resolver" intro={data.decision} /><Section tone="section-tint" title="Criterios para comparar"><CardGrid items={data.criteria} /></Section><Section title="Cuándo elegir cada alternativa"><CardGrid items={data.options} /></Section><Section tone="section-tint" title="Soluciones comerciales relacionadas"><RelatedSolutions market={market} slugs={[data.primary, data.secondary]} /></Section><Section title="Siguiente paso"><RelatedSolutions market={market} slugs={[data.nextStep, 'planes']} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'comparison', marketCode: market, data })} /><FinalCta market={market} title="Toma la decisión con una línea base verificable" actionLabel={data.nextStep === 'planes' ? 'Comparar planes' : 'Solicitar una auditoría'} target={data.nextStep} /></>; }

export function AboutGrowthPage() { const market = useMarket(); return <><Head market={market} routePath="nosotros" title="Sobre Pixvo Growth System" description="Conoce el enfoque, límites y forma de trabajo de Pixvo para operar sistemas de crecimiento digital." /><Breadcrumbs market={market} items={[{ label: 'Nosotros' }]} /><Hero market={market} eyebrow="Nosotros" title="Un sistema operado con criterio y supervisión humana" lead="Pixvo integra SEO, automatización, inteligencia artificial con supervisión humana, analítica, WordPress y seguimiento de oportunidades." /><Section title="Cómo trabajamos" intro="Auditamos, priorizamos, implementamos y medimos dentro de un alcance definido. No prometemos posiciones ni sustituimos al equipo comercial." /><Section title="Capacidad deliberadamente limitada"><CardGrid items={['Máximo inicial de cuatro clientes activos', 'Máximo de un onboarding nuevo por mes', 'Trabajo recurrente con alcance definido', 'Transparencia sobre límites y dependencias']} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'about', marketCode: market })} /><FinalCta market={market} /></>; }
export function ContactGrowthPage() { const market = useMarket(); return <><Head market={market} routePath="contacto" title={`Contacto de Pixvo en ${markets[market].name}`} description="Contacta con Pixvo por WhatsApp o teléfono para consultar sobre SEO, automatización, analítica y sistemas de crecimiento digital." /><Breadcrumbs market={market} items={[{ label: 'Contacto' }]} /><Hero market={market} eyebrow="Contacto" title="Cuéntanos qué está frenando tu sistema comercial" lead="El diagnóstico reúne el contexto necesario para valorar el encaje. También puedes comunicarte con Pixvo por WhatsApp o teléfono." /><Section title="Habla con Pixvo" intro="Atendemos de forma remota a empresas que necesitan conectar captación orgánica, conversión, automatización y seguimiento de leads."><div className="contact-options"><a className="contact-option contact-option--whatsapp" href={contactConfig.whatsappUrl} target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>{contactConfig.whatsappPhone}</strong><small>Iniciar conversación</small></a>{contactConfig.phones.map((phone) => <a className="contact-option" key={phone.href} href={phone.href}><span>{phone.label}</span><strong>{phone.display}</strong><small>Llamar a Pixvo</small></a>)}</div></Section><Section tone="section-tint" title="¿Prefieres aportar el contexto por escrito?" intro="Completa la solicitud de diagnóstico para que podamos revisar tu tráfico, medición, procesos y capacidad de atención antes de recomendar un plan." /><FinalCta market={market} title="Empieza por una solicitud de diagnóstico" /></>; }
export function CasesPage() {
  const market = useMarket();
  const socialCase = caseStudies[0];
  return <><Head market={market} routePath="casos-de-exito" title="Casos, proyectos y transformaciones verificables | Pixvo" description="Casos de trabajo y experiencia asociada: problemas, soluciones, transformación funcional, métricas disponibles y límites de evidencia explícitos." image={socialCase.socialImage || socialCase.image} imageWidth={socialCase.socialImageWidth || socialCase.imageWidth} imageHeight={socialCase.socialImageHeight || socialCase.imageHeight} /><Breadcrumbs market={market} items={[{ label: 'Casos de éxito' }]} /><Hero market={market} eyebrow="Casos y proyectos" title="Transformaciones explicadas desde el problema y la evidencia" lead="Separamos hechos verificables, cambio funcional, métricas disponibles y límites de atribución. Cuando no existe una cifra pública, no la sustituimos por una estimación." visual={socialCase} /><Section title="Casos destacados" intro="Microcuotas es el caso cuantificable principal. Hospital Metropolitano se presenta como experiencia asociada del equipo con atribución pública explícita; los demás documentan transformación funcional sin inventar métricas."><CaseStudyGrid items={caseStudies} market={market} /></Section><Section title="Cómo leer estos casos"><CardGrid items={['Problema e impacto operativo documentados', 'Solución explicada por su función, no por una lista de tecnologías', 'Antes y después limitado a cambios comprobables', 'Métricas y límites de evidencia identificados por separado']} /></Section><EditorialExpansion sections={getEditorialExpansion({ pageType: 'case_index', marketCode: market })} /><FinalCta market={market} title="¿Qué transformación necesita documentar tu empresa?" actionLabel="Compartir el contexto del proceso" /></>;
}

export function CaseStudyPage() {
  const market = useMarket();
  const { slug } = useParams();
  const item = getCaseStudyBySlug(slug);
  if (!item) return <Navigate to="/404" replace />;
  const routePath = `casos-de-exito/${slug}`;
  const crumbs = [{ label: 'Casos de éxito', path: localPath(market, 'casos-de-exito') }, { label: item.title, path: localPath(market, routePath) }];
  const creator = item.slug === 'hospital-metropolitano'
    ? [{ '@type': 'Organization', name: 'Metamorfosis 360' }, { '@type': 'Organization', name: 'Events Group' }]
    : { '@type': 'Organization', name: 'Pixvo' };
  const socialImage = item.socialImage || item.image;
  const imageObject = { '@type': 'ImageObject', url: new URL(socialImage, DOMAIN).toString(), width: item.socialImageWidth || item.imageWidth, height: item.socialImageHeight || item.imageHeight, caption: item.caption || item.imageAlt };
  const schema = { '@context': 'https://schema.org', '@type': 'WebPage', name: `Caso: ${item.title}`, description: item.summary, image: imageObject, mainEntity: { '@type': 'CreativeWork', name: item.title, abstract: item.summary, image: imageObject, creator } };
  const relatedCases = getRelatedCaseStudies(item);
  return <>
    <Head market={market} routePath={routePath} title={`Caso: ${item.title} | Pixvo`} description={item.summary} image={socialImage} imageWidth={item.socialImageWidth || item.imageWidth} imageHeight={item.socialImageHeight || item.imageHeight} schema={[schema, breadcrumbSchema(market, crumbs)]} />
    <Breadcrumbs market={market} items={[{ label: 'Casos de éxito', to: localPath(market, 'casos-de-exito') }, { label: item.title }]} />
    <Hero market={market} eyebrow={item.label} title={item.title} lead={item.summary} visual={item.slug === 'hospital-metropolitano' ? undefined : item} />
    {item.slug === 'hospital-metropolitano' && <CaseStudyMedia item={item} />}
    <Section title="Resumen ejecutivo" intro={item.executiveSummary} />
    <Section tone="section-tint" title="Situación inicial" intro={item.situation} />
    <Section title="Problema" intro={item.problem} />
    <Section tone="section-tint" title="Impacto operativo del problema" intro={item.operationalImpact} />
    <Section title="Solución" intro={item.solution} />
    <Section tone="section-tint" title="Cómo funciona"><CaseStudyProcess items={item.workflow} /></Section>
    <Section title="Arquitectura y decisiones técnicas" intro={item.architecture} />
    <Section tone="section-tint" title="Antes vs. después"><BeforeAfter items={item.beforeAfter} /></Section>
    <Section title="Resultado verificable" intro={item.result} />
    {item.metrics.length > 0 && <Section tone="section-tint" title="Métricas verificables" intro="Cada cifra conserva el contexto de su etapa; no se combinan eventos distintos del funnel."><VerifiedMetrics items={item.metrics} /></Section>}
    <Section title="Hechos verificables"><EvidenceList items={item.verifiedFacts} /></Section>
    {item.attribution && <Section tone="section-tint" title="Atribución pública" intro={item.attribution} />}
    <Section title="Limitaciones de evidencia" intro={item.caveat} />
    <Section tone="section-tint" title="Servicios y capacidades relacionadas"><CaseCommercialLinks market={market} links={item.commercialLinks} /></Section>
    {relatedCases.length > 0 && <Section title="Otros casos relacionados"><CaseStudyGrid items={relatedCases} market={market} /></Section>}
    <EditorialExpansion sections={getEditorialExpansion({ pageType: 'case_study', marketCode: market, data: item })} />
    <FinalCta market={market} title="¿Tu empresa tiene un cuello de botella parecido?" description="Comparte el proceso actual y la evidencia disponible. Separaremos los hechos, las limitaciones y el siguiente paso antes de recomendar una implementación." actionLabel="Analicemos qué parte de este proceso puedes automatizar" />
  </>;
}

export function ThankYouPage() { const market = useMarket(); return <><Head market={market} routePath="gracias-diagnostico" title="Solicitud recibida | Pixvo" description="Confirmación de recepción de la solicitud de diagnóstico." robots="noindex,follow" /><section className="thank-you"><div><span className="eyebrow">Solicitud recibida</span><h1>Gracias por compartir tu contexto</h1><p>Hemos registrado la solicitud. La recepción no implica aceptación ni una promesa de respuesta inmediata. Revisaremos el encaje y los datos disponibles antes de indicar el siguiente paso.</p><a className="button button--secondary" href={localPath(market)}>Volver a Pixvo</a></div></section></>; }

export function LegacyRedirect({ to }) { const location = useLocation(); return <Navigate replace to={`${to}${location.search}`} />; }
