import { Navigate, useParams } from 'react-router-dom';
import { Container } from '../components/common/Container';
import { SeoHead } from '../components/common/SeoHead';

const pages = {
  'aviso-legal': ['Aviso legal', 'Esta página identifica las condiciones generales de uso del sitio. Los datos fiscales y registrales definitivos no están publicados porque requieren aprobación del responsable.', [['Contenido del sitio', 'La información describe el alcance de Pixvo Growth System. La garantía de tráfico solo se aplica al volumen y al KPI definidos por escrito para cada proyecto; no constituye una promesa de posiciones concretas ni de ventas.'], ['Responsabilidad', 'El usuario debe validar que las soluciones y condiciones se adecuan a su situación antes de contratar.']]],
  'politica-de-privacidad': ['Política de privacidad', 'Información sobre el tratamiento asociado al formulario de diagnóstico.', [['Datos tratados', 'El formulario prepara la identificación profesional, el contexto de la empresa, los datos de contacto y los criterios de encaje facilitados por la persona usuaria.'], ['Envío mediante WhatsApp', 'Al continuar, los datos se incorporan a un mensaje de WhatsApp dirigido a Pixvo. La persona usuaria revisa y confirma manualmente el envío, que queda sujeto también a las condiciones y políticas de WhatsApp.'], ['Finalidad y conservación', 'Los datos enviados se utilizan para revisar la solicitud y responder. El responsable debe completar y aprobar identidad, base jurídica, plazos de conservación y canales de ejercicio de derechos antes de activar la recepción en producción.'], ['Analítica', 'Los eventos analíticos no incluyen nombre, correo, empresa, sitio web ni otros datos personales del formulario.']]],
  'politica-de-cookies': ['Política de cookies', 'La activación de herramientas que almacenen identificadores debe acompañarse de una solución de consentimiento y de información aprobada.', [['Configuración actual', 'El código admite una configuración externa de analítica, pero no incorpora identificadores de medición ni una plataforma de consentimiento por defecto.'], ['Preferencias', 'No se deben activar cookies no necesarias hasta configurar el mecanismo y los textos aplicables.']]],
  'condiciones-del-servicio': ['Condiciones del servicio', 'Resumen informativo de alcance; no sustituye las condiciones contractuales aprobadas.', [['Alcance', 'Los planes operan con unidades mensuales, límites, revisiones y permanencia indicados en la página del mercado correspondiente.'], ['Garantía de tráfico', 'Cada proyecto define por escrito una línea base, un volumen objetivo de tráfico, la fuente de medición y las condiciones aplicables. Si el KPI no se alcanza y se cumplen esas condiciones, la continuidad se bonifica durante tres meses en Core y Growth o seis meses en Scale para trabajar hasta alcanzar el resultado acordado.'], ['Exclusiones', 'No se garantizan posiciones concretas ni ventas. La oferta, el precio, la atención, la negociación y el cierre permanecen bajo responsabilidad de la empresa. Tampoco se incluyen cambios ilimitados, soporte permanente, gestión comercial de leads ni desarrollo completo de software.'], ['Contratación', 'Precio, fiscalidad, disponibilidad, KPI y condiciones definitivas se confirman antes de contratar.']]],
};
export default function LegalPage() {
  const { slug } = useParams(); const page = pages[slug]; if (!page) return <Navigate to="/404" replace />;
  return <><SeoHead title={`${page[0]} | Pixvo`} description={page[1]} path={`/legal/${slug}/`} robots="noindex,follow" /><section className="legal-page"><Container size="narrow"><span className="eyebrow">Información legal</span><h1>{page[0]}</h1><p className="lead">{page[1]}</p>{page[2].map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</Container></section></>;
}
